Align results of array_first_value/array_last_value with access by index.
VKCOM/kphp-polyfills pull request #4
Opened 2020-11-17 15:10 UTC by vkaverin

Return `null` for an empty array.

2020-11-19 12:36 UTC, unserialize submitted a review, later dismissed

2020-11-19 12:38 UTC, unserialize commented
Can you please rename the commit message according to our code style? From a small letter, without a period at the end

2020-11-19 12:47 UTC, vkaverin commented
Sure. Pushed.

2020-11-19 12:52 UTC, unserialize approved these changes

2020-12-14 00:48 UTC, rybakit requested changes

2020-12-14 00:48 UTC, rybakit commented on kphp_polyfills.php
>    return current($a);
```suggestion
  return $a ? reset($a) : null;
```

2020-12-14 00:48 UTC, rybakit commented on kphp_polyfills.php
>    return current($a);
```suggestion
  return $a ? end($a) : null;
```

2021-02-24 11:06 UTC, unserialize approved these changes

2021-02-24 11:06 UTC, merged